"""SOC Incident Response AI Agent - Mock Analysis"""

from datetime import datetime

class IRAgent:
    def __init__(self):
        print("✅ IR Agent initialized!")
    
    def parse_alert(self, alert_data):
        print("\n[STEP 1] Parsing alert...")
        
        parsed = {
            "alert_id": alert_data.get("id"),
            "rule_description": alert_data.get("rule", {}).get("description"),
            "severity_level": alert_data.get("rule", {}).get("level"),
            "source_ip": alert_data.get("data", {}).get("srcip"),
            "destination_ip": alert_data.get("data", {}).get("dstip"),
            "full_log": alert_data.get("full_log"),
            "agent_name": alert_data.get("agent", {}).get("name"),
        }
        
        print(f"✅ Alert parsed!")
        print(f"   Rule: {parsed['rule_description']}")
        print(f"   Source: {parsed['source_ip']}")
        return parsed
    
    def analyze_alert(self, parsed_alert):
        print("\n[STEP 2] AI Analysis...")
        
        analysis = f"""## Severity Assessment
HIGH - Requires immediate attention

## Attack Type
{parsed_alert['rule_description']}

## Recommended Actions
1. Block source IP {parsed_alert['source_ip']}
2. Review firewall logs
3. Check for lateral movement
4. Investigate account compromise
5. Reset affected credentials

## Business Impact
CRITICAL - Potential system compromise

## Risk Level
{parsed_alert['severity_level']}/15 = HIGH PRIORITY"""
        
        print("✅ Analysis complete!")
        return analysis
    
    def generate_report(self, parsed_alert, analysis):
        print("\n[STEP 3] Generating report...")
        
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S UTC")
        
        report = f"""# 📋 Incident Response Report
**Generated:** {timestamp}

## Alert Summary
- **Alert ID:** {parsed_alert['alert_id']}
- **Rule:** {parsed_alert['rule_description']}
- **Severity:** {parsed_alert['severity_level']}/15
- **Source IP:** {parsed_alert['source_ip']}
- **Destination IP:** {parsed_alert['destination_ip']}

## Full Log
{parsed_alert['full_log']}

## Analysis
{analysis}

## Actions
- [ ] Investigate source
- [ ] Block IP if malicious
- [ ] Review logs
- [ ] Document findings

---
*Generated by SOC IR AI Agent*
"""
        print("✅ Report generated!")
        return report
    
    def send_notification(self, parsed_alert):
        print("\n[STEP 4] Notifications...")
        severity = parsed_alert['severity_level']
        emoji = "🔴" if severity > 10 else "🟡"
        print(f"✅ Ready: {emoji} {parsed_alert['rule_description']}")
    
    def process_alert(self, alert_data):
        print("\n" + "="*60)
        print("🚀 INCIDENT RESPONSE AGENT ACTIVATED!")
        print("="*60)
        
        try:
            parsed = self.parse_alert(alert_data)
            analysis = self.analyze_alert(parsed)
            report = self.generate_report(parsed, analysis)
            self.send_notification(parsed)
            
            print("\n" + "="*60)
            print("✅ INCIDENT RESPONSE COMPLETE!")
            print("="*60)
            
            return {"status": "success", "report": report}
        except Exception as e:
            print(f"\n❌ ERROR: {e}")
            return {"status": "error", "message": str(e)}